baseURL = "https://all-phase-masonry.github.io"
title = "All Phase Masonry"
author = "KilPen Tech"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = [ "tella", "hugo-snap-gallery" ]
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  showBlog = false
  mainSections = ['projects']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo2.jpg"
    alt = "All Phase Masonry Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "All Phase Masonry"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Oahu's leading masonry company for the authentic polynesian vibe."
    meta_og_title = "All Phase Masonry"
    meta_og_type = "website"
    meta_og_url = "https://allphasehawaii.com"
    meta_og_image = "https://allphasehawaii.com/static/img/tn.png"
    meta_og_description = "A Oahu's leading masonry company for the authentic polynesian vibe.Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@allphasemasonry"
    meta_twitter_creator = "@allphasemasonry"

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Our Work"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "products"
    name = "Our Services"
    url = "/products/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
	
  [[menu.main]]
    identifier = "testimonials"
    name = "Testimonials"
    url = "/testimonials/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

  # Footer Menu
#  [[menu.footer]]
#    name = "Home"
#    url = "/"
#      weight = 1

  [[menu.footer]]
    name = "Yelp"
    url = "https://www.yelp.com/biz/all-phase-masonry-waipahu-2"
    pre = "<i class='fa-brands fa-yelp text-2xl'></i>"
      weight = 1

  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/allphasemasonry_hawaii/"
    pre = "<i class='fa-brands fa-instagram text-2xl'></i>"
      weight = 1